# .github/secret_scanning.yml
push_protection:
  enabled: true
allow:
  - name: "Google Cloud Service Account Credentials"
    paths:
      - "src/_old/firebase/zapp-passenger-2019-firebase-adminsdk-5p9v8-2ff7de2cf8.json"
      - "src/_old/firebase/zapp-driver-2019-firebase-adminsdk-55mv8-6e41c603e4.json"
